

-- Tabela TB_DEZENA
CREATE TABLE "LOTERIA"."TB_DEZENA" 
 (	"DEZ_ID" NUMBER(2,0) NOT NULL ENABLE, 
 CONSTRAINT "TB_DEZENA_PK" PRIMARY KEY ("DEZ_ID")
 ; 
 
REM INSERTING into TB_DEZENA
Insert into TB_DEZENA (DEZ_ID) values (1);
Insert into TB_DEZENA (DEZ_ID) values (2);
Insert into TB_DEZENA (DEZ_ID) values (3);
Insert into TB_DEZENA (DEZ_ID) values (4);
Insert into TB_DEZENA (DEZ_ID) values (5);
Insert into TB_DEZENA (DEZ_ID) values (6);
Insert into TB_DEZENA (DEZ_ID) values (7);
Insert into TB_DEZENA (DEZ_ID) values (8);
Insert into TB_DEZENA (DEZ_ID) values (9);
Insert into TB_DEZENA (DEZ_ID) values (10);
Insert into TB_DEZENA (DEZ_ID) values (11);
Insert into TB_DEZENA (DEZ_ID) values (12);
Insert into TB_DEZENA (DEZ_ID) values (13);
Insert into TB_DEZENA (DEZ_ID) values (14);
Insert into TB_DEZENA (DEZ_ID) values (15);
Insert into TB_DEZENA (DEZ_ID) values (16);
Insert into TB_DEZENA (DEZ_ID) values (17);
Insert into TB_DEZENA (DEZ_ID) values (18);
Insert into TB_DEZENA (DEZ_ID) values (19);
Insert into TB_DEZENA (DEZ_ID) values (20);
Insert into TB_DEZENA (DEZ_ID) values (21);
Insert into TB_DEZENA (DEZ_ID) values (22);
Insert into TB_DEZENA (DEZ_ID) values (23);
Insert into TB_DEZENA (DEZ_ID) values (24);
Insert into TB_DEZENA (DEZ_ID) values (25);


-- Tabela TB_CONCURSO
CREATE TABLE "LOTERIA"."TB_CONCURSO" 
 (	"CONC_ID" NUMBER(6,0) NOT NULL ENABLE, 
"CONC_NUMERO" NUMBER(6,0) NOT NULL ENABLE, 
 CONSTRAINT "TB_CONCURSO_PK" PRIMARY KEY ("CONC_ID")    
;
  
CREATE SEQUENCE  "LOTERIA"."SEQ_CONCURSO"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
 

-- Tabela TB_CONCURSO_DEZENA
CREATE TABLE "LOTERIA"."TB_CONCURSO_DEZENA" 
 (	"CONC_ID" NUMBER(6,0) NOT NULL ENABLE, 
"DEZ_ID" NUMBER(2,0) NOT NULL ENABLE, 
 CONSTRAINT "TB_CONCURSO_DEZENA_PK" PRIMARY KEY ("CONC_ID", "DEZ_ID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "USERS"  ENABLE, 
 CONSTRAINT "TB_CONCURSO_DEZENA_TB_CON_FK1" FOREIGN KEY ("CONC_ID")
  REFERENCES "LOTERIA"."TB_CONCURSO" ("CONC_ID") ON DELETE CASCADE ENABLE, 
 CONSTRAINT "TB_CONCURSO_DEZENA_TB_DEZ_FK1" FOREIGN KEY ("DEZ_ID")
  REFERENCES "LOTERIA"."TB_DEZENA" ("DEZ_ID") ENABLE
 ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "USERS" ;
 
-- Tabela TB_BILHETE
  CREATE TABLE "LOTERIA"."TB_BILHETE" 
   (	"BILH_ID" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "TB_BILHETE_PK" PRIMARY KEY ("BILH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 

   CREATE SEQUENCE  "LOTERIA"."SEQ_BILHETE"  MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
 

-- Tabela TB_BILHETE_DEZENA

  CREATE TABLE "LOTERIA"."TB_BILHETE_DEZENA" 
   (	"BILH_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"DEZ_ID" NUMBER(2,0) NOT NULL ENABLE, 
	 CONSTRAINT "TB_BILHETE_DEZENA_PK" PRIMARY KEY ("BILH_ID", "DEZ_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "TB_BILHETE_DEZENA_TB_BILH_FK1" FOREIGN KEY ("BILH_ID")
	  REFERENCES "LOTERIA"."TB_BILHETE" ("BILH_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "TB_BILHETE_DEZENA_TB_DEZE_FK1" FOREIGN KEY ("DEZ_ID")
	  REFERENCES "LOTERIA"."TB_DEZENA" ("DEZ_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 


 
